### ISSUE TITLE
Fetch FCM tokens for multiple users in a single query

### ISSUE THREAD

**Issue by mchudy** [leancodepl/corelibrary#189] opened 2021-01-08 14:36 UTC
In `IPushNotificationTokenStore`

```csharp
public Task<Dictionary<string, List<string>>> GetTokensAsync(
    IEnumerable<Guid> userIds,
    CancellationToken cancellationToken = default(CancellationToken))
```

**Comment by jakubfijalkowski** [comment] 2021-01-08 17:07
Duplicate of #92?

**Comment by mchudy** [comment] 2021-01-08 17:26
Not quite, those are on different levels of abstraction. `SendToMultipleUsersAsync` is a nice shortcut, but it won't work with localized notifications (when you need to send one `MulticastMessage` for each locale). But I guess they both address the same problem (with this one giving some more elasticity). Depends on how many convenience methods we want to have in the core lib really.

**Closed as completed** 2021-01-11 12:44 UTC
Labels: enhancement, good first issue, area-firebase
