### ISSUE TITLE
SendGridClient does not throw when tries to send message with empty subject

### ISSUE THREAD

**Issue by lukaszgarstecki** [leancodepl/corelibrary#72] opened 2020-07-14 15:00 UTC
Expected behaviour: failure

Actual behaviour: result returned has code 400 (no subject)

**Comment by Saancreed** [comment] 2020-07-15 12:05
It's _sort of_ by design: awaiting the `Send` operation gives a result object which the user is supposed to inspect for errors.

But since we have some breaking changes incoming soonish. we could consider returning simply a `Task` that might end up in faulted state instead.

**Comment by lukaszgarstecki** [comment] 2020-07-15 12:08
Oh, well this bad request does not say what is wrong anyway, so it does not benefit us to chceck result anyway

**Comment by Saancreed** [comment] 2020-07-22 11:41
Closed by #82

**Closed as completed by Saancreed** 2020-07-22 11:41 UTC
Labels: bug
